version: "2"

services: 
    postgresql:
        hostname: kpostgres
        image: bitnami/postgresql:latest
        environment:
        - POSTGRESQL_USERNAME=guest
        - POSTGRESQL_PASSWORD=guest
        - POSTGRESQL_DATABASE=notesdb
        ports: 
        - "5432:5432"
